orbs:
  aws-ecr: circleci/aws-ecr@6.8.1
  aws-ecs: circleci/aws-ecs@1.1.0
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build_and_push_image: 
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'ecr-registory'
          tag: '${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update: 
                requires:
                  - aws-ecr/build_and_push_image
                family: 'ecr-test'
                cluster-name: 'default-kim5'
                container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
