orbs:
  aws-ecr: circleci/aws-ecr@1.0.0
  aws-ecs: circleci/aws-ecs@0.0.6
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - aws-ecr/build_and_push_image: 
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'nginx'
          tag: '${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update: 
                requires:
                  - aws-ecr/build_and_push_image
                family: 'kim-app-nginx'
                cluster-name: 'default-kim5'
                container-image-name-updates: 'container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}:${CIRCLE_SHA1}'
#hoge
